spring.application.name=NaariRaksha-Backend
server.port=8080

# For testing, we use H2 (In-memory SQL) instead of MySQL so you can run it immediately
spring.datasource.url=jdbc:h2:mem:naariraksha_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update

# Allow access to H2 console from browser
spring.h2.console.settings.web-allow-others=true
